# Generated by Django 2.2.3 on 2019-07-27 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangolyteevents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='changed',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='hide_end_date',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='hide_start_date',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='online_event',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('D', 'draft'), ('L', 'live'), ('S', 'started'), ('E', 'ended'), ('CO', 'completed'), ('CA', 'canceled')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
