# Generated by Django 2.2.3 on 2019-07-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangolyteevents', '0002_auto_20190727_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_id',
            field=models.CharField(default='uniquevalue1', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
