# Generated by Django 2.2.3 on 2019-07-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangolyteevents', '0003_event_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
