# Generated by Django 2.2.3 on 2019-07-29 21:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangolyteevents', '0004_auto_20190729_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_available_tickets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='maximum_ticket_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=8),
        ),
        migrations.AddField(
            model_name='event',
            name='minimum_ticket_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=8),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
