# Generated by Django 2.2.3 on 2019-07-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangolyteevents', '0005_auto_20190729_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
