# Generated by Django 2.2.3 on 2019-07-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangolyteevents', '0006_event_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer_description',
            field=models.TextField(blank=True),
        ),
    ]
