# Generated by Django 2.2.3 on 2019-07-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangolyteevents', '0008_auto_20190729_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
