# Generated by Django 2.2.3 on 2019-07-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangolyteevents', '0009_auto_20190729_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
